networks:
  memowisenet:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - ${SQL_SERVER_PORT}:1433
    networks:
      - memowisenet
      
  rabbitmq:
    image: rabbitmq:4.0-management
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    networks:
      - memowisenet
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: MemoWise.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,${SQL_SERVER_PORT};Database=210170;User Id=sa;Password=${MSSQL_SA_PASSWORD};ConnectRetryCount=0;TrustServerCertificate=True
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL}
      - STRIPE_SK=${STRIPE_SK}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_VIRTUAL_HOST=${RABBITMQ_VIRTUAL_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${API_PORT}:8080
    networks:
      - memowisenet
    depends_on:
      - sqlserver

  subscriber_email:
    restart: unless-stopped
    build:
      context: .
      dockerfile: MemoWise.SubscriberEmail/Dockerfile
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL=${EMAIL}
      - SENDER_USERNAME=${SENDER_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
    networks:
      - memowisenet
    depends_on:
      rabbitmq:
        condition: service_healthy
